### ISSUE TITLE
Cannot join the room with another browser

### ISSUE THREAD

**Issue by zhaofeng-shu33** [EmreBeratKR/Fireboy-and-Watergirl-3D#1]
This method expects any address to include a port. The final ':' in addressAndPort has to separate it.
             IPv6 addresses have multiple colons and <b>must use brackets</b> to separate address from port.
            I have limited knowledge on how it works behind the two-player game. As I figured out from client side, the two instances open different addresses to the `xxx.exitgames.com` server. So there is server-client communication basically. So I wonder whether this game support two players on different devices?
![image](https://user-images.githubusercontent.com/23316477/217785744-9f68c54a-2ebc-498c-8d1c-4ed77c0feaeb.png)

**Comment by EmreBeratKR** [comment]
Hello,

Thanks for reaching out!
This project uses Photon services so the online side is completely handled by the Photon Pun 2 SDK.
As I tested right now, you should be able to connect different devices includes both PC and mobile.

To solve your problem you may create the room with that name "1234567" before joining in.
Hope that helps :)

**Comment by zhaofeng-shu33** [comment]
Sorry I still cannot reproduce your success. Is there limitation on the dev regions of Photon? I am in China.

**Comment by zhaofeng-shu33** [comment]
I use overseas VPN and it works. By [the official documentation](https://doc.photonengine.com/pun/current/connection-and-authentication/regions#using_the_chinese_mainland_region) I found the region of China is specifically mentioned. Maybe it causes my problem. PUN 2 is a good solution. Maybe I need to deploy a server in my region to obtain low latency.

**Comment by EmreBeratKR** [comment]
I see, hope you fix the latecy problem somehow.
I'am closing the issue right now. You can open another issue if you face with an issue again.

**Comment by zhaofeng-shu33** [comment]
Thank you very much.
